// Creates infrastructure/docker/.stack.env once: the secrets the containerised stack needs and
// that must never be committed (an ES256 key pair for access tokens, the AI service token).
// `pnpm stack:up` runs this first; the file is git-ignored and reused on later runs.
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';

const file = new URL('.stack.env', import.meta.url);
if (!existsSync(file)) {
  const { privateKey, publicKey } = generateKeyPairSync('ec', {
    namedCurve: 'P-256',
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  const escape = (pem) => pem.trim().replace(/\n/g, '\\n');
  writeFileSync(
    file,
    [
      '# Generated by stack-env.mjs for the local containerised stack. Not for any real deployment.',
      `JWT_PRIVATE_KEY="${escape(privateKey)}"`,
      `JWT_PUBLIC_KEY="${escape(publicKey)}"`,
      `AI_SERVICE_TOKEN=${randomBytes(32).toString('hex')}`,
      '',
    ].join('\n'),
    { mode: 0o600 },
  );
  console.log('Created infrastructure/docker/.stack.env (local secrets for the stack).');
}
