"""Prometheus metrics for the AI service (architecture §11).

Served on METRICS_PORT (default 9464) by prometheus_client's own server, a port the proxy never
routes. Labels are bounded: routes are templates, features are route paths, models come from
configuration.
"""

import time
from contextvars import ContextVar

import structlog
from prometheus_client import Counter, Histogram, start_http_server
from starlette.types import ASGIApp, Message, Receive, Scope, Send

_log = structlog.get_logger(__name__)

LATENCY_BUCKETS = (0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60)

HTTP_DURATION = Histogram(
    "forge_ai_http_request_duration_seconds",
    "AI service HTTP requests by route, method and status, until the last byte (streams too)",
    ["method", "route", "status"],
    buckets=LATENCY_BUCKETS,
)

LLM_DURATION = Histogram(
    "forge_llm_request_duration_seconds",
    "Model provider calls by feature, operation, model and outcome",
    ["feature", "operation", "model", "outcome"],
    buckets=LATENCY_BUCKETS,
)

LLM_TOKENS = Counter(
    "forge_llm_tokens_total",
    "Tokens sent to (input) and generated by (output) the model provider",
    ["feature", "model", "direction"],
)

LLM_COST = Counter(
    "forge_llm_cost_usd_total",
    "Estimated provider cost in USD (the same estimate recorded in ai_usage)",
    ["feature", "model"],
)

# The feature on whose behalf a provider call is made: the route path of the request.
current_feature: ContextVar[str] = ContextVar("current_feature", default="unknown")


class MetricsMiddleware:
    """Times each request to its last byte and labels it by route template.

    Pure ASGI rather than BaseHTTPMiddleware, so a streamed answer is measured until it ends,
    not until its headers are sent.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        started = time.perf_counter()
        status = 500
        token = current_feature.set(scope["path"])

        async def send_and_observe(message: Message) -> None:
            nonlocal status
            if message["type"] == "http.response.start":
                status = message["status"]
            await send(message)

        try:
            await self.app(scope, receive, send_and_observe)
        finally:
            current_feature.reset(token)
            HTTP_DURATION.labels(
                method=scope["method"],
                route=route_template(scope),
                status=str(status),
            ).observe(time.perf_counter() - started)


def route_template(scope: Scope) -> str:
    """The matched route as a template ("/v1/drafts", "/v1/documents/{document_id}").

    Built from the request path and its matched path parameters, because with nested routers
    FastAPI records the innermost route, whose path lacks the parents' prefixes.
    """
    if scope.get("route") is None:
        return "unmatched"
    segments = scope["path"].split("/")
    names = {str(value): name for name, value in scope.get("path_params", {}).items()}
    return "/".join(f"{{{names[part]}}}" if part in names else part for part in segments)


def start_metrics_server(port: int) -> bool:
    """Serves /metrics on its own port (0 turns it off, as in tests).

    A port already in use is logged, not fatal: metrics are not worth refusing to start.
    """
    if not port:
        return False
    try:
        start_http_server(port)
    except OSError as error:
        _log.warning("metrics port in use; metrics are off", port=port, error=str(error))
        return False
    return True
