-- Forge initial schema.
--
-- Generated by `prisma migrate diff` from prisma/schema.prisma, then extended by hand with
-- what Prisma cannot express (marked "Hand-written" below): extensions, generated columns,
-- CHECK constraints, partial and vector indexes, an audit-log immutability trigger,
-- reference data and the AI service's restricted role. docs/database.md explains each one.

-- Extensions (idempotent; on RDS the master user may create these).
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

-- CreateEnum
CREATE TYPE "issue_status" AS ENUM ('BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'CANCELLED');

-- CreateEnum
CREATE TYPE "issue_priority" AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');

-- CreateEnum
CREATE TYPE "issue_type" AS ENUM ('BUG', 'FEATURE', 'TASK', 'CHORE');

-- CreateEnum
CREATE TYPE "issue_event_type" AS ENUM ('CREATED', 'FIELD_CHANGED', 'COMMENT_ADDED', 'COMMENT_EDITED', 'COMMENT_DELETED', 'ATTACHMENT_ADDED', 'ATTACHMENT_REMOVED', 'LABEL_ADDED', 'LABEL_REMOVED', 'SPRINT_CHANGED', 'LINKED', 'DELETED', 'RESTORED');

-- CreateEnum
CREATE TYPE "sprint_status" AS ENUM ('PLANNED', 'ACTIVE', 'COMPLETED');

-- CreateEnum
CREATE TYPE "sprint_issue_outcome" AS ENUM ('COMPLETED', 'CARRIED_OVER', 'REMOVED');

-- CreateEnum
CREATE TYPE "attachment_status" AS ENUM ('PENDING_UPLOAD', 'AVAILABLE');

-- CreateEnum
CREATE TYPE "notification_type" AS ENUM ('ISSUE_ASSIGNED', 'COMMENT_ADDED', 'MENTIONED', 'SPRINT_STARTED', 'SPRINT_COMPLETED', 'PULL_REQUEST_OPENED', 'AI_JOB_COMPLETED', 'AI_JOB_FAILED');

-- CreateEnum
CREATE TYPE "github_account_type" AS ENUM ('USER', 'ORGANIZATION');

-- CreateEnum
CREATE TYPE "pull_request_state" AS ENUM ('OPEN', 'CLOSED', 'MERGED');

-- CreateEnum
CREATE TYPE "issue_link_type" AS ENUM ('PULL_REQUEST', 'COMMIT');

-- CreateEnum
CREATE TYPE "document_source_type" AS ENUM ('ISSUE', 'COMMENT', 'PULL_REQUEST', 'COMMIT', 'UPLOAD');

-- CreateEnum
CREATE TYPE "ai_message_role" AS ENUM ('USER', 'ASSISTANT', 'TOOL');

-- CreateEnum
CREATE TYPE "ai_job_type" AS ENUM ('ISSUE_SUMMARY', 'PR_REVIEW', 'REINDEX');

-- CreateEnum
CREATE TYPE "ai_job_status" AS ENUM ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "ai_feature" AS ENUM ('ISSUE_DRAFT', 'ISSUE_SUMMARY', 'RELATED_ISSUES', 'CHAT', 'SEMANTIC_SEARCH', 'PR_REVIEW', 'EMBEDDING');

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "email" CITEXT NOT NULL,
    "display_name" VARCHAR(100) NOT NULL,
    "password_hash" TEXT NOT NULL,
    "avatar_url" TEXT,
    "is_admin" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "last_login_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "roles" (
    "id" SMALLINT NOT NULL,
    "key" VARCHAR(32) NOT NULL,
    "name" VARCHAR(64) NOT NULL,
    "description" TEXT,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token_hash" CHAR(64) NOT NULL,
    "family_id" UUID NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "used_at" TIMESTAMPTZ,
    "revoked_at" TIMESTAMPTZ,
    "user_agent" VARCHAR(512),
    "ip_address" INET,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "password_reset_tokens" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token_hash" CHAR(64) NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "used_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teams" (
    "id" UUID NOT NULL,
    "name" CITEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "teams_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "team_members" (
    "team_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "added_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "team_members_pkey" PRIMARY KEY ("team_id","user_id")
);

-- CreateTable
CREATE TABLE "projects" (
    "id" UUID NOT NULL,
    "key" VARCHAR(10) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "issue_seq" INTEGER NOT NULL DEFAULT 0,
    "default_assignee_id" UUID,
    "created_by_id" UUID NOT NULL,
    "archived_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_members" (
    "project_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role_id" SMALLINT NOT NULL,
    "added_by_id" UUID,
    "added_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "project_members_pkey" PRIMARY KEY ("project_id","user_id")
);

-- CreateTable
CREATE TABLE "labels" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "name" CITEXT NOT NULL,
    "color" CHAR(7) NOT NULL,
    "description" TEXT,

    CONSTRAINT "labels_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "issues" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "number" INTEGER NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "description" TEXT,
    "type" "issue_type" NOT NULL DEFAULT 'TASK',
    "status" "issue_status" NOT NULL DEFAULT 'BACKLOG',
    "priority" "issue_priority" NOT NULL DEFAULT 'MEDIUM',
    "reporter_id" UUID NOT NULL,
    "assignee_id" UUID,
    "story_points" SMALLINT,
    "due_date" DATE,
    "version" INTEGER NOT NULL DEFAULT 1,
    "resolved_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "search_vector" tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce("title", '')), 'A') ||
        setweight(to_tsvector('english', coalesce("description", '')), 'B')
    ) STORED,

    CONSTRAINT "issues_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "issue_labels" (
    "issue_id" UUID NOT NULL,
    "label_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "added_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "issue_labels_pkey" PRIMARY KEY ("issue_id","label_id")
);

-- CreateTable
CREATE TABLE "issue_comments" (
    "id" UUID NOT NULL,
    "issue_id" UUID NOT NULL,
    "author_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "edited_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "issue_comments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "issue_events" (
    "id" BIGSERIAL NOT NULL,
    "issue_id" UUID NOT NULL,
    "actor_id" UUID,
    "type" "issue_event_type" NOT NULL,
    "field" VARCHAR(64),
    "old_value" JSONB,
    "new_value" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "issue_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attachments" (
    "id" UUID NOT NULL,
    "issue_id" UUID NOT NULL,
    "uploaded_by_id" UUID NOT NULL,
    "file_name" VARCHAR(255) NOT NULL,
    "content_type" VARCHAR(127) NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "storage_key" VARCHAR(512) NOT NULL,
    "status" "attachment_status" NOT NULL DEFAULT 'PENDING_UPLOAD',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "attachments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sprints" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "goal" TEXT,
    "status" "sprint_status" NOT NULL DEFAULT 'PLANNED',
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "started_at" TIMESTAMPTZ,
    "completed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "sprints_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sprint_issues" (
    "id" BIGSERIAL NOT NULL,
    "sprint_id" UUID NOT NULL,
    "issue_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "story_points_at_add" SMALLINT,
    "added_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "removed_at" TIMESTAMPTZ,
    "outcome" "sprint_issue_outcome",

    CONSTRAINT "sprint_issues_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "type" "notification_type" NOT NULL,
    "payload" JSONB NOT NULL,
    "read_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" BIGSERIAL NOT NULL,
    "actor_id" UUID,
    "action" VARCHAR(100) NOT NULL,
    "entity_type" VARCHAR(50),
    "entity_id" VARCHAR(100),
    "ip_address" INET,
    "user_agent" VARCHAR(512),
    "request_id" VARCHAR(128),
    "metadata" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "outbox_events" (
    "id" BIGSERIAL NOT NULL,
    "aggregate_type" VARCHAR(50) NOT NULL,
    "aggregate_id" VARCHAR(100) NOT NULL,
    "event_type" VARCHAR(100) NOT NULL,
    "payload" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "published_at" TIMESTAMPTZ,

    CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "github_installations" (
    "id" UUID NOT NULL,
    "installation_id" BIGINT NOT NULL,
    "account_login" VARCHAR(100) NOT NULL,
    "account_type" "github_account_type" NOT NULL,
    "installed_by_id" UUID,
    "suspended_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "github_installations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "github_repositories" (
    "id" UUID NOT NULL,
    "installation_id" UUID NOT NULL,
    "github_id" BIGINT NOT NULL,
    "full_name" VARCHAR(200) NOT NULL,
    "default_branch" VARCHAR(255) NOT NULL,
    "is_private" BOOLEAN NOT NULL,
    "html_url" TEXT NOT NULL,
    "last_synced_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "github_repositories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_repositories" (
    "project_id" UUID NOT NULL,
    "repository_id" UUID NOT NULL,
    "linked_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "project_repositories_pkey" PRIMARY KEY ("project_id","repository_id")
);

-- CreateTable
CREATE TABLE "github_pull_requests" (
    "id" UUID NOT NULL,
    "repository_id" UUID NOT NULL,
    "github_id" BIGINT NOT NULL,
    "number" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT,
    "state" "pull_request_state" NOT NULL,
    "is_draft" BOOLEAN NOT NULL DEFAULT false,
    "author_login" VARCHAR(100),
    "head_ref" VARCHAR(255) NOT NULL,
    "head_sha" CHAR(40) NOT NULL,
    "base_ref" VARCHAR(255) NOT NULL,
    "additions" INTEGER,
    "deletions" INTEGER,
    "changed_files" INTEGER,
    "html_url" TEXT NOT NULL,
    "opened_at" TIMESTAMPTZ NOT NULL,
    "merged_at" TIMESTAMPTZ,
    "closed_at" TIMESTAMPTZ,
    "github_updated_at" TIMESTAMPTZ NOT NULL,
    "synced_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "github_pull_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "github_commits" (
    "id" UUID NOT NULL,
    "repository_id" UUID NOT NULL,
    "sha" CHAR(40) NOT NULL,
    "message" TEXT NOT NULL,
    "author_login" VARCHAR(100),
    "author_name" VARCHAR(200),
    "committed_at" TIMESTAMPTZ NOT NULL,
    "html_url" TEXT NOT NULL,
    "synced_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "github_commits_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "github_contributors" (
    "repository_id" UUID NOT NULL,
    "login" VARCHAR(100) NOT NULL,
    "avatar_url" TEXT,
    "contributions" INTEGER NOT NULL,
    "synced_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "github_contributors_pkey" PRIMARY KEY ("repository_id","login")
);

-- CreateTable
CREATE TABLE "issue_links" (
    "id" UUID NOT NULL,
    "issue_id" UUID NOT NULL,
    "link_type" "issue_link_type" NOT NULL,
    "pull_request_id" UUID,
    "commit_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "issue_links_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "documents" (
    "id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "source_type" "document_source_type" NOT NULL,
    "source_id" UUID,
    "title" VARCHAR(300) NOT NULL,
    "content" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "content_hash" CHAR(64) NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_by_id" UUID,
    "indexed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "document_chunks" (
    "id" BIGSERIAL NOT NULL,
    "document_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "chunk_index" INTEGER NOT NULL,
    "content" TEXT NOT NULL,
    "token_count" INTEGER NOT NULL,
    "heading_path" TEXT,
    "content_hash" CHAR(64) NOT NULL,
    "embedding_model" VARCHAR(100) NOT NULL,
    "embedding" vector(1536) NOT NULL,
    "search_vector" tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce("heading_path", '')), 'A') ||
        setweight(to_tsvector('english', "content"), 'B')
    ) STORED,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "document_chunks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_conversations" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "project_id" UUID,
    "title" VARCHAR(200) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "ai_conversations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_messages" (
    "id" UUID NOT NULL,
    "conversation_id" UUID NOT NULL,
    "role" "ai_message_role" NOT NULL,
    "content" TEXT NOT NULL,
    "citations" JSONB,
    "model" VARCHAR(100),
    "input_tokens" INTEGER,
    "output_tokens" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_jobs" (
    "id" UUID NOT NULL,
    "type" "ai_job_type" NOT NULL,
    "status" "ai_job_status" NOT NULL DEFAULT 'QUEUED',
    "requested_by_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "input" JSONB NOT NULL,
    "result" JSONB,
    "error" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMPTZ,
    "finished_at" TIMESTAMPTZ,

    CONSTRAINT "ai_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_summaries" (
    "id" UUID NOT NULL,
    "issue_id" UUID NOT NULL,
    "thread_hash" CHAR(64) NOT NULL,
    "content" JSONB NOT NULL,
    "model" VARCHAR(100) NOT NULL,
    "prompt_version" VARCHAR(50) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_summaries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_reviews" (
    "id" UUID NOT NULL,
    "pull_request_id" UUID NOT NULL,
    "head_sha" CHAR(40) NOT NULL,
    "summary" TEXT NOT NULL,
    "findings" JSONB NOT NULL,
    "missing_tests" JSONB NOT NULL,
    "model" VARCHAR(100) NOT NULL,
    "prompt_version" VARCHAR(50) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_usage" (
    "id" BIGSERIAL NOT NULL,
    "user_id" UUID,
    "project_id" UUID,
    "feature" "ai_feature" NOT NULL,
    "model" VARCHAR(100) NOT NULL,
    "prompt_version" VARCHAR(50),
    "input_tokens" INTEGER NOT NULL,
    "output_tokens" INTEGER NOT NULL DEFAULT 0,
    "latency_ms" INTEGER NOT NULL,
    "cost_usd" DECIMAL(12,6) NOT NULL,
    "success" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_usage_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "roles_key_key" ON "roles"("key");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");

-- CreateIndex
CREATE INDEX "refresh_tokens_family_id_idx" ON "refresh_tokens"("family_id");

-- CreateIndex
CREATE UNIQUE INDEX "password_reset_tokens_token_hash_key" ON "password_reset_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "password_reset_tokens_user_id_idx" ON "password_reset_tokens"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "teams_name_key" ON "teams"("name");

-- CreateIndex
CREATE INDEX "team_members_user_id_idx" ON "team_members"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "projects_key_key" ON "projects"("key");

-- CreateIndex
CREATE INDEX "project_members_user_id_idx" ON "project_members"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "labels_project_id_name_key" ON "labels"("project_id", "name");

-- CreateIndex
CREATE UNIQUE INDEX "labels_id_project_id_key" ON "labels"("id", "project_id");

-- CreateIndex
CREATE INDEX "issues_assignee_id_status_idx" ON "issues"("assignee_id", "status");

-- CreateIndex
CREATE INDEX "issues_title_trgm_idx" ON "issues" USING GIN ("title" gin_trgm_ops);

-- CreateIndex
CREATE UNIQUE INDEX "issues_project_id_number_key" ON "issues"("project_id", "number");

-- CreateIndex
CREATE UNIQUE INDEX "issues_id_project_id_key" ON "issues"("id", "project_id");

-- CreateIndex
CREATE INDEX "issue_labels_label_id_idx" ON "issue_labels"("label_id");

-- CreateIndex
CREATE INDEX "issue_comments_issue_id_created_at_idx" ON "issue_comments"("issue_id", "created_at");

-- CreateIndex
CREATE INDEX "issue_events_issue_id_created_at_idx" ON "issue_events"("issue_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "attachments_storage_key_key" ON "attachments"("storage_key");

-- CreateIndex
CREATE INDEX "attachments_issue_id_idx" ON "attachments"("issue_id");

-- CreateIndex
CREATE UNIQUE INDEX "sprints_project_id_name_key" ON "sprints"("project_id", "name");

-- CreateIndex
CREATE UNIQUE INDEX "sprints_id_project_id_key" ON "sprints"("id", "project_id");

-- CreateIndex
CREATE INDEX "sprint_issues_sprint_id_idx" ON "sprint_issues"("sprint_id");

-- CreateIndex
CREATE INDEX "sprint_issues_issue_id_idx" ON "sprint_issues"("issue_id");

-- CreateIndex
CREATE INDEX "notifications_user_id_created_at_idx" ON "notifications"("user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs"("created_at" DESC);

-- CreateIndex
CREATE INDEX "audit_logs_actor_id_created_at_idx" ON "audit_logs"("actor_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "audit_logs_entity_type_entity_id_idx" ON "audit_logs"("entity_type", "entity_id");

-- CreateIndex
CREATE UNIQUE INDEX "github_installations_installation_id_key" ON "github_installations"("installation_id");

-- CreateIndex
CREATE UNIQUE INDEX "github_repositories_github_id_key" ON "github_repositories"("github_id");

-- CreateIndex
CREATE INDEX "github_repositories_installation_id_idx" ON "github_repositories"("installation_id");

-- CreateIndex
CREATE INDEX "project_repositories_repository_id_idx" ON "project_repositories"("repository_id");

-- CreateIndex
CREATE UNIQUE INDEX "github_pull_requests_github_id_key" ON "github_pull_requests"("github_id");

-- CreateIndex
CREATE INDEX "github_pull_requests_repository_id_state_opened_at_idx" ON "github_pull_requests"("repository_id", "state", "opened_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "github_pull_requests_repository_id_number_key" ON "github_pull_requests"("repository_id", "number");

-- CreateIndex
CREATE INDEX "github_commits_repository_id_committed_at_idx" ON "github_commits"("repository_id", "committed_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "github_commits_repository_id_sha_key" ON "github_commits"("repository_id", "sha");

-- CreateIndex
CREATE INDEX "issue_links_pull_request_id_idx" ON "issue_links"("pull_request_id");

-- CreateIndex
CREATE INDEX "issue_links_commit_id_idx" ON "issue_links"("commit_id");

-- CreateIndex
CREATE UNIQUE INDEX "issue_links_issue_id_pull_request_id_key" ON "issue_links"("issue_id", "pull_request_id");

-- CreateIndex
CREATE UNIQUE INDEX "issue_links_issue_id_commit_id_key" ON "issue_links"("issue_id", "commit_id");

-- CreateIndex
CREATE INDEX "documents_project_id_source_type_idx" ON "documents"("project_id", "source_type");

-- CreateIndex
CREATE UNIQUE INDEX "documents_source_type_source_id_key" ON "documents"("source_type", "source_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_id_project_id_key" ON "documents"("id", "project_id");

-- CreateIndex
CREATE INDEX "document_chunks_project_id_idx" ON "document_chunks"("project_id");

-- CreateIndex
CREATE UNIQUE INDEX "document_chunks_document_id_chunk_index_key" ON "document_chunks"("document_id", "chunk_index");

-- CreateIndex
CREATE INDEX "ai_conversations_user_id_updated_at_idx" ON "ai_conversations"("user_id", "updated_at" DESC);

-- CreateIndex
CREATE INDEX "ai_messages_conversation_id_created_at_idx" ON "ai_messages"("conversation_id", "created_at");

-- CreateIndex
CREATE INDEX "ai_jobs_requested_by_id_created_at_idx" ON "ai_jobs"("requested_by_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "ai_jobs_project_id_type_created_at_idx" ON "ai_jobs"("project_id", "type", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "ai_summaries_issue_id_thread_hash_key" ON "ai_summaries"("issue_id", "thread_hash");

-- CreateIndex
CREATE UNIQUE INDEX "ai_reviews_pull_request_id_head_sha_key" ON "ai_reviews"("pull_request_id", "head_sha");

-- CreateIndex
CREATE INDEX "ai_usage_created_at_idx" ON "ai_usage"("created_at" DESC);

-- CreateIndex
CREATE INDEX "ai_usage_user_id_created_at_idx" ON "ai_usage"("user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "ai_usage_project_id_created_at_idx" ON "ai_usage"("project_id", "created_at" DESC);

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "projects" ADD CONSTRAINT "projects_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "projects" ADD CONSTRAINT "projects_default_assignee_id_fkey" FOREIGN KEY ("default_assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_added_by_id_fkey" FOREIGN KEY ("added_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "labels" ADD CONSTRAINT "labels_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issues" ADD CONSTRAINT "issues_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issues" ADD CONSTRAINT "issues_reporter_id_fkey" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issues" ADD CONSTRAINT "issues_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_labels" ADD CONSTRAINT "issue_labels_issue_id_project_id_fkey" FOREIGN KEY ("issue_id", "project_id") REFERENCES "issues"("id", "project_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_labels" ADD CONSTRAINT "issue_labels_label_id_project_id_fkey" FOREIGN KEY ("label_id", "project_id") REFERENCES "labels"("id", "project_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_labels" ADD CONSTRAINT "issue_labels_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_comments" ADD CONSTRAINT "issue_comments_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_comments" ADD CONSTRAINT "issue_comments_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_events" ADD CONSTRAINT "issue_events_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_events" ADD CONSTRAINT "issue_events_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_uploaded_by_id_fkey" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sprints" ADD CONSTRAINT "sprints_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sprint_issues" ADD CONSTRAINT "sprint_issues_sprint_id_project_id_fkey" FOREIGN KEY ("sprint_id", "project_id") REFERENCES "sprints"("id", "project_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sprint_issues" ADD CONSTRAINT "sprint_issues_issue_id_project_id_fkey" FOREIGN KEY ("issue_id", "project_id") REFERENCES "issues"("id", "project_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sprint_issues" ADD CONSTRAINT "sprint_issues_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "github_installations" ADD CONSTRAINT "github_installations_installed_by_id_fkey" FOREIGN KEY ("installed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "github_repositories" ADD CONSTRAINT "github_repositories_installation_id_fkey" FOREIGN KEY ("installation_id") REFERENCES "github_installations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_repositories" ADD CONSTRAINT "project_repositories_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_repositories" ADD CONSTRAINT "project_repositories_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "github_repositories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "github_pull_requests" ADD CONSTRAINT "github_pull_requests_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "github_repositories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "github_commits" ADD CONSTRAINT "github_commits_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "github_repositories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "github_contributors" ADD CONSTRAINT "github_contributors_repository_id_fkey" FOREIGN KEY ("repository_id") REFERENCES "github_repositories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_links" ADD CONSTRAINT "issue_links_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_links" ADD CONSTRAINT "issue_links_pull_request_id_fkey" FOREIGN KEY ("pull_request_id") REFERENCES "github_pull_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issue_links" ADD CONSTRAINT "issue_links_commit_id_fkey" FOREIGN KEY ("commit_id") REFERENCES "github_commits"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_document_id_project_id_fkey" FOREIGN KEY ("document_id", "project_id") REFERENCES "documents"("id", "project_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_conversations" ADD CONSTRAINT "ai_conversations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_conversations" ADD CONSTRAINT "ai_conversations_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_messages" ADD CONSTRAINT "ai_messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "ai_conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_jobs" ADD CONSTRAINT "ai_jobs_requested_by_id_fkey" FOREIGN KEY ("requested_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_jobs" ADD CONSTRAINT "ai_jobs_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_summaries" ADD CONSTRAINT "ai_summaries_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_reviews" ADD CONSTRAINT "ai_reviews_pull_request_id_fkey" FOREIGN KEY ("pull_request_id") REFERENCES "github_pull_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_usage" ADD CONSTRAINT "ai_usage_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_usage" ADD CONSTRAINT "ai_usage_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ═══════════════════════════ Hand-written ═══════════════════════════

-- ---------- Business-rule CHECK constraints ----------
-- The API validates all of these too; the database is the last line of defence against a
-- bug, a script or a manual fix writing an impossible state.

ALTER TABLE "users"
    ADD CONSTRAINT "users_display_name_not_blank" CHECK (length(btrim("display_name")) > 0);

ALTER TABLE "refresh_tokens"
    ADD CONSTRAINT "refresh_tokens_token_hash_hex" CHECK ("token_hash" ~ '^[0-9a-f]{64}$');
ALTER TABLE "password_reset_tokens"
    ADD CONSTRAINT "password_reset_tokens_token_hash_hex" CHECK ("token_hash" ~ '^[0-9a-f]{64}$');

ALTER TABLE "projects"
    ADD CONSTRAINT "projects_key_format" CHECK ("key" ~ '^[A-Z][A-Z0-9]{1,9}$'),
    ADD CONSTRAINT "projects_name_not_blank" CHECK (length(btrim("name")) > 0),
    ADD CONSTRAINT "projects_issue_seq_non_negative" CHECK ("issue_seq" >= 0);

ALTER TABLE "labels"
    ADD CONSTRAINT "labels_color_hex" CHECK ("color" ~ '^#[0-9a-fA-F]{6}$'),
    ADD CONSTRAINT "labels_name_not_blank" CHECK (length(btrim("name")) > 0);

ALTER TABLE "issues"
    ADD CONSTRAINT "issues_number_positive" CHECK ("number" > 0),
    ADD CONSTRAINT "issues_title_not_blank" CHECK (length(btrim("title")) > 0),
    ADD CONSTRAINT "issues_story_points_range" CHECK ("story_points" BETWEEN 0 AND 100),
    ADD CONSTRAINT "issues_version_positive" CHECK ("version" > 0),
    -- resolved_at is set exactly when the issue is in a terminal status.
    ADD CONSTRAINT "issues_resolved_at_matches_status"
        CHECK (("status" IN ('DONE', 'CANCELLED')) = ("resolved_at" IS NOT NULL));

ALTER TABLE "attachments"
    ADD CONSTRAINT "attachments_size_limit" CHECK ("size_bytes" BETWEEN 1 AND 10485760);

ALTER TABLE "sprints"
    ADD CONSTRAINT "sprints_dates_ordered" CHECK ("end_date" >= "start_date"),
    -- Lifecycle timestamps must agree with the status (PLANNED → ACTIVE → COMPLETED).
    ADD CONSTRAINT "sprints_status_timestamps" CHECK (
        ("status" = 'PLANNED'   AND "started_at" IS NULL     AND "completed_at" IS NULL) OR
        ("status" = 'ACTIVE'    AND "started_at" IS NOT NULL AND "completed_at" IS NULL) OR
        ("status" = 'COMPLETED' AND "started_at" IS NOT NULL AND "completed_at" IS NOT NULL)
    );

ALTER TABLE "sprint_issues"
    -- An outcome is recorded exactly when the issue leaves the sprint.
    ADD CONSTRAINT "sprint_issues_outcome_when_removed"
        CHECK (("removed_at" IS NULL) = ("outcome" IS NULL));

ALTER TABLE "issue_links"
    ADD CONSTRAINT "issue_links_single_target" CHECK (
        ("link_type" = 'PULL_REQUEST' AND "pull_request_id" IS NOT NULL AND "commit_id" IS NULL) OR
        ("link_type" = 'COMMIT'       AND "commit_id" IS NOT NULL       AND "pull_request_id" IS NULL)
    );

ALTER TABLE "github_pull_requests"
    ADD CONSTRAINT "github_pull_requests_head_sha_hex" CHECK ("head_sha" ~ '^[0-9a-f]{40}$');
ALTER TABLE "github_commits"
    ADD CONSTRAINT "github_commits_sha_hex" CHECK ("sha" ~ '^[0-9a-f]{40}$');
ALTER TABLE "ai_reviews"
    ADD CONSTRAINT "ai_reviews_head_sha_hex" CHECK ("head_sha" ~ '^[0-9a-f]{40}$');

ALTER TABLE "documents"
    -- Uploaded documents are their own source; every other source type points at a row.
    ADD CONSTRAINT "documents_source_id_presence"
        CHECK (("source_type" = 'UPLOAD') = ("source_id" IS NULL));

ALTER TABLE "document_chunks"
    ADD CONSTRAINT "document_chunks_chunk_index_non_negative" CHECK ("chunk_index" >= 0),
    ADD CONSTRAINT "document_chunks_token_count_positive" CHECK ("token_count" > 0);

ALTER TABLE "ai_usage"
    ADD CONSTRAINT "ai_usage_non_negative" CHECK (
        "input_tokens" >= 0 AND "output_tokens" >= 0 AND "latency_ms" >= 0 AND "cost_usd" >= 0
    );

-- ---------- Partial, expression and special-purpose indexes ----------

-- At most one ACTIVE sprint per project (FR-5.1), enforced even under concurrent "start sprint".
CREATE UNIQUE INDEX "sprints_one_active_per_project"
    ON "sprints" ("project_id") WHERE "status" = 'ACTIVE';

-- An issue is in at most one sprint at a time; history rows (removed_at set) are unlimited.
CREATE UNIQUE INDEX "sprint_issues_one_current_sprint_per_issue"
    ON "sprint_issues" ("issue_id") WHERE "removed_at" IS NULL;

-- Board/list queries only ever read non-deleted issues, so index only those.
CREATE INDEX "issues_active_by_status_idx"
    ON "issues" ("project_id", "status") WHERE "deleted_at" IS NULL;
-- Default list order (most recently updated first) with id as the cursor tie-breaker.
CREATE INDEX "issues_active_by_updated_idx"
    ON "issues" ("project_id", "updated_at" DESC, "id" DESC) WHERE "deleted_at" IS NULL;
-- Keyword search (FR-11.1).
CREATE INDEX "issues_search_vector_idx" ON "issues" USING GIN ("search_vector");

-- Unread badge: tiny index, because most notifications are read.
CREATE INDEX "notifications_unread_idx"
    ON "notifications" ("user_id") WHERE "read_at" IS NULL;

-- Outbox relay scans unpublished events oldest first; published rows drop out of the index.
CREATE INDEX "outbox_events_unpublished_idx"
    ON "outbox_events" ("id") WHERE "published_at" IS NULL;

-- Approximate nearest-neighbour search over embeddings (cosine distance). HNSW needs no
-- training step (unlike IVFFlat), so it can be built on an empty table and stays accurate as
-- rows are added. pgvector 0.8 iterative scans keep recall high when combined with the
-- project_id filter (SET hnsw.iterative_scan = relaxed_order at query time).
CREATE INDEX "document_chunks_embedding_hnsw_idx"
    ON "document_chunks" USING hnsw ("embedding" vector_cosine_ops) WITH (m = 16, ef_construction = 64);
CREATE INDEX "document_chunks_search_vector_idx" ON "document_chunks" USING GIN ("search_vector");

-- ---------- Append-only audit log (FR-13) ----------

CREATE FUNCTION "audit_logs_reject_modification"() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only (% rejected)', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$;

CREATE TRIGGER "audit_logs_append_only"
    BEFORE UPDATE OR DELETE ON "audit_logs"
    FOR EACH ROW EXECUTE FUNCTION "audit_logs_reject_modification"();
-- TRUNCATE bypasses row triggers, so block it separately.
CREATE TRIGGER "audit_logs_no_truncate"
    BEFORE TRUNCATE ON "audit_logs"
    FOR EACH STATEMENT EXECUTE FUNCTION "audit_logs_reject_modification"();

-- ---------- Reference data ----------

INSERT INTO "roles" ("id", "key", "name", "description") VALUES
    (1, 'PROJECT_MANAGER', 'Project Manager', 'Manages project settings, members and sprints'),
    (2, 'DEVELOPER',       'Developer',       'Creates and works on issues'),
    (3, 'VIEWER',          'Viewer',          'Read-only access');

-- ---------- Least-privilege role for the AI service (ADR-0004) ----------
-- A NOLOGIN group role holding only the grants the AI service needs. Login users are created
-- outside migrations (docker init script locally, Terraform in AWS) so no password is ever
-- committed, and are made members of this role.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'forge_ai') THEN
        CREATE ROLE forge_ai NOLOGIN;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO forge_ai;
GRANT SELECT, INSERT, UPDATE, DELETE ON "documents", "document_chunks" TO forge_ai;
GRANT INSERT ON "ai_usage" TO forge_ai;
GRANT USAGE ON SEQUENCE "document_chunks_id_seq", "ai_usage_id_seq" TO forge_ai;
